name: Docker Image CI

on: [push]
env:
  DOCKER_CLI_EXPERIMENTAL: enabled
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pre setup cleanup
        run: sudo apt-get remove docker docker-engine docker.io containerd runc
      - name: install docker ssl cert
        run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - name: add docker repository
        run: sudo add-apt-repository "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - name: update apt
        run: sudo apt update
      - name: install prerequisites
        run: sudo apt -y install qemu-user qemu-user-binfmt
      - name: update docker
        run: sudo apt install -y docker-ce
      - name: enable multi-arch
        run: sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: docker login
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: create docker builder
        run: docker buildx create --use --driver docker-container --name multibuilder
      - name: bootstrap docker builder
        run: docker buildx inspect --bootstrap
      - name: check docker version
        run: docker version ; docker buildx ls ; docker buildx inspect multibuilder
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t daverichmond/pgadmin4:latest --push .
